import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';
import express from 'express';
import request from 'supertest';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

vi.mock('./storage', () => ({ deleteFile: vi.fn().mockResolvedValue(undefined) }));
vi.mock('./imageProcessing', () => ({ processUploadedImage: vi.fn().mockResolvedValue({ display: Buffer.from('display'), thumbnail: Buffer.from('thumb'), width: 1200, height: 800 }) }));
vi.mock('./storage/processed', () => ({ storeProcessedImages: vi.fn().mockResolvedValue({ url: '/uploaded.webp', thumbnailUrl: '/uploaded-thumb.webp' }) }));
const directory = mkdtempSync(join(tmpdir(), 'fluent-albums-test-'));
process.env.GALLERY_DB_PATH = join(directory, 'gallery.db');
const { initDatabase, closeDatabase, dbAll, dbRun } = await import('../database/db');
const { PhotoDao } = await import('../database/dao/photoDao');
const { AlbumDao } = await import('../database/dao/albumDao');
const { default: authRouter } = await import('./auth');
const { default: albumsRouter } = await import('./routes/albums');
const { default: photosRouter } = await import('./routes/photos');
const { deleteFile } = await import('./storage');
const app = express();
app.use(express.json());
app.use('/api/auth', authRouter);
app.use('/api/albums', albumsRouter);
app.use('/api/photos', photosRouter);
const agent = request.agent(app);
const photos = new PhotoDao();
const albums = new AlbumDao();
const input = { url: '/test.webp', thumbnail_url: '/thumb.webp', title: '测试照片', year: 2026, width: 1200, height: 800, tags: ['风景'] };
const albumInput = (photoIds: string[], published = false) => ({ name: '测试画册', description: '简介', published, coverPhotoId: null, photoIds });
beforeAll(async () => { await initDatabase(); await agent.post('/api/auth/login').send({ password: 'admin123' }).expect(200); });
afterAll(async () => { await closeDatabase(); rmSync(directory, { recursive: true, force: true }); });

describe('albums and photo integration', () => {
  it('protects all management routes, hides drafts, rejects empty publication', async () => {
    await request(app).get('/api/albums/admin').expect(401);
    await request(app).post('/api/albums').send(albumInput([])).expect(401);
    await request(app).put('/api/albums/order').send({ ids: [] }).expect(401);
    await request(app).post('/api/albums/members').send({}).expect(401);
    await request(app).put('/api/albums/any').send({}).expect(401);
    await request(app).delete('/api/albums/any').expect(401);
    await agent.post('/api/albums').send(albumInput([], true)).expect(400);
    await photos.createPhoto(input, 'draft-photo');
    const draft = await agent.post('/api/albums').send(albumInput(['draft-photo'])).expect(201);
    const id = draft.body.data.id;
    await request(app).get(`/api/albums/${id}`).expect(404);
    await request(app).get(`/api/albums/admin/${id}`).expect(401);
    expect((await request(app).get('/api/albums')).body.data).toEqual([]);
    expect((await request(app).get('/api/photos/draft-photo')).body.data.albums).toBeUndefined();
    await agent.put(`/api/albums/${id}`).send(albumInput(['draft-photo'], true)).expect(200);
    expect((await request(app).get(`/api/albums/${id}`)).body.data.photos.map((p: any) => p.id)).toEqual(['draft-photo']);
  });
  it('supports shared membership, ordered photos, cover independence and duplicate skipping', async () => {
    await photos.createPhoto(input, 'one'); await photos.createPhoto(input, 'two'); await photos.createPhoto(input, 'three');
    const a = (await albums.save(null, { ...albumInput(['two', 'one'], true), coverPhotoId: 'one' }))!;
    const b = (await albums.save(null, albumInput(['one'])))!;
    await agent.post('/api/albums/members').send({ albumIds: [a.id, b.id], photoIds: ['one', 'three', 'three'] }).expect(200);
    expect((await albums.detail(a.id))?.photos.map(p => p?.id)).toEqual(['two', 'one', 'three']);
    expect((await albums.list()).find(row => row.id === a.id)?.previews[0]?.id).toBe('one');
    const page = await photos.getPhotosPage({ page: 1, pageSize: 30, albumId: b.id });
    expect(page.total).toBe(2);
    expect(page.items.find(p => p.id === 'one')?.albums.map(album => album.id).sort()).toEqual([a.id, b.id].sort());
    await photos.updatePhoto('one', { title: '已更新', albumIds: [b.id] });
    expect((await albums.detail(b.id, true))?.photos.find(p => p?.id === 'one')?.title).toBe('已更新');
    expect((await albums.list()).find(row => row.id === a.id)?.coverPhotoId).toBe('two');
    await albums.delete(b.id);
    expect(await photos.getPhotoById('one')).not.toBeNull();
  });
  it('cascades single and batch photo deletion and hides published empty albums', async () => {
    await photos.createPhoto(input, 'delete-one'); await photos.createPhoto(input, 'delete-two');
    const a = (await albums.save(null, { ...albumInput(['delete-one', 'delete-two'], true), coverPhotoId: 'delete-one' }))!;
    await agent.delete('/api/photos/delete-one').expect(200);
    expect((await albums.list()).find(row => row.id === a.id)).toMatchObject({ photoCount: 1, coverPhotoId: 'delete-two' });
    await agent.delete('/api/photos/batch').send({ ids: ['delete-two'] }).expect(200);
    await request(app).get(`/api/albums/${a.id}`).expect(404);
    expect((await albums.list()).some(row => row.id === a.id)).toBe(false);
    expect((await albums.list(true)).find(row => row.id === a.id)).toMatchObject({ published: true, photoCount: 0 });
  });
  it('rolls back every database row when a batch delete fails midway', async () => {
    await photos.createPhoto(input, 'batch-rollback-one');
    await photos.createPhoto(input, 'batch-rollback-two');
    await dbRun("CREATE TRIGGER reject_batch_delete BEFORE DELETE ON photos WHEN OLD.id = 'batch-rollback-two' BEGIN SELECT RAISE(ABORT, 'forced failure'); END");
    await expect(photos.batchDeletePhotos(['batch-rollback-one', 'batch-rollback-two'])).rejects.toThrow('forced failure');
    expect(await photos.getPhotoById('batch-rollback-one')).not.toBeNull();
    expect(await photos.getPhotoById('batch-rollback-two')).not.toBeNull();
    await dbRun('DROP TRIGGER reject_batch_delete');
  });
  it('rolls back invalid changes and preserves album order across concurrent additions', async () => {
    const a = (await albums.save(null, albumInput(['one'])))!;
    await agent.put(`/api/albums/${a.id}`).send({ ...albumInput(['missing']), name: '不应保存' }).expect(400);
    expect((await albums.detail(a.id, true))?.name).toBe('测试画册');
    await expect(photos.createPhoto({ ...input, albumIds: ['missing'] }, 'rollback-photo')).rejects.toThrow();
    expect(await photos.getPhotoById('rollback-photo')).toBeNull();
    await expect(photos.updatePhoto('one', { title: '不应保存', albumIds: ['missing'] })).rejects.toThrow();
    expect((await photos.getPhotoById('one'))?.title).toBe('已更新');
    await Promise.all([albums.addPhotos([a.id], ['two']), albums.addPhotos([a.id], ['three'])]);
    const members = await dbAll<{ position: number }>('SELECT position FROM album_photos WHERE album_id = ?', [a.id]);
    expect(new Set(members.map(row => row.position)).size).toBe(3);
    const order = (await albums.list(true)).map(row => row.id).reverse();
    await agent.put('/api/albums/order').send({ ids: order }).expect(200);
    expect((await albums.list(true)).map(row => row.id)).toEqual(order);
    await agent.put('/api/albums/order').send({ ids: [] }).expect(400);
  });
  it('allows an already published album to become empty without exposing it publicly', async () => {
    const album = (await albums.save(null, albumInput(['one'], true)))!;
    await agent.put(`/api/albums/${album.id}`).send(albumInput([], true)).expect(200);
    await request(app).get(`/api/albums/${album.id}`).expect(404);
    expect((await albums.list(true)).find(row => row.id === album.id)).toMatchObject({ published: true, photoCount: 0 });
    await agent.put(`/api/albums/${album.id}`).send(albumInput([], false)).expect(200);
    await agent.put(`/api/albums/${album.id}`).send(albumInput([], true)).expect(400);
  });
  it('uploads and associates atomically, cleans stored images on failure, and positions retries before later photos', async () => {
    const a = (await albums.save(null, albumInput(['one'])))!;
    const upload = (title: string, ids: string[], before?: string[]) => agent.post('/api/photos/upload').field('metadata', JSON.stringify({ title, year: 2026, albumIds: ids, albumBeforePhotoIds: before })).attach('file', Buffer.from('jpeg'), 'sample.jpg');
    const count = (await photos.getAllPhotos()).length;
    await upload('失败', ['missing']).expect(400);
    expect((await photos.getAllPhotos()).length).toBe(count);
    expect(deleteFile).toHaveBeenCalledWith('/uploaded.webp');
    expect(deleteFile).toHaveBeenCalledWith('/uploaded-thumb.webp');
    const later = await upload('队列第二张', [a.id]).expect(201);
    const retry = await upload('队列第一张重试', [a.id], [later.body.data.id]).expect(201);
    expect((await albums.detail(a.id, true))?.photos.map(p => p?.id)).toEqual(['one', retry.body.data.id, later.body.data.id]);
  });
});
