import React, { useState } from 'react';
import { ArrowLeft, LockKeyhole } from 'lucide-react';
import { Link } from 'react-router-dom';
import { authService } from '../../services/authService';
export function AdminLogin({ onSuccess }: { onSuccess: () => void }) {
  const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { await authService.login(password); onSuccess(); } catch (reason) { setError(reason instanceof Error ? reason.message : '登录失败，请重试'); } finally { setLoading(false); } };
  return <div className="admin-shell studio-login relative grid min-h-screen place-items-center bg-slate-100 px-4 py-16"><Link to="/" className="absolute left-4 top-4 inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-medium text-slate-600 transition hover:bg-white hover:text-slate-950 sm:left-6 sm:top-6"><ArrowLeft size={17} />返回图库</Link><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-8 shadow-xl shadow-slate-900/8"><div className="mb-7 text-center"><div className="studio-login-emblem" aria-hidden="true">f<span>.</span></div><p className="studio-login-brand">Fluent Gallery</p><h1 className="text-2xl font-semibold text-slate-950">管理员登录</h1><p className="mt-2 text-sm text-slate-500">登录后管理图库与系统设置</p></div><label className="block text-sm font-medium text-slate-700">密码<div className="relative mt-2"><LockKeyhole className="absolute left-3 top-3 text-slate-400" size={18} /><input autoFocus required autoComplete="current-password" type="password" value={password} onChange={event => setPassword(event.target.value)} className="w-full rounded-xl border border-slate-300 py-2.5 pl-10 pr-3 text-slate-900" placeholder="输入管理员密码" /></div></label>{error && <p role="alert" className="mt-3 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-xl bg-blue-600 py-2.5 font-medium text-white transition hover:bg-blue-700 disabled:opacity-60">{loading ? '正在登录…' : '进入控制台'}</button></form></div>;
}
