import React, { useEffect, useState } from 'react';
import { Download, Eye, FileText, RefreshCw, Search, Trash2, X } from 'lucide-react';
import { LogEntry, LogFile, logService } from '../../services/logService';
import { SelectMenu } from '../SelectMenu';

function ConfirmClear({ file, onCancel, onConfirm }: { file: string; onCancel: () => void; onConfirm: () => void }) { return <div role="dialog" aria-modal="true" className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-lg font-semibold text-slate-950">清空日志？</h2><p className="mt-2 text-sm leading-6 text-slate-600">将清空 {file || '全部日志文件'}，此操作不可恢复。</p><div className="mt-6 flex justify-end gap-3"><button onClick={onCancel} className="rounded-xl border border-slate-300 px-4 py-2 text-sm">取消</button><button autoFocus onClick={onConfirm} className="rounded-xl bg-red-600 px-4 py-2 text-sm font-medium text-white">确认清空</button></div></div></div>; }

export function LogsPanel({ onSessionExpired }: { onSessionExpired: () => void }) {
  const [files, setFiles] = useState<LogFile[]>([]); const [file, setFile] = useState(''); const [level, setLevel] = useState(''); const [query, setQuery] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [logs, setLogs] = useState<LogEntry[]>([]); const [loading, setLoading] = useState(true); const [autoRefresh, setAutoRefresh] = useState(false); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [pages, setPages] = useState(0); const [selected, setSelected] = useState<LogEntry | null>(null); const [confirming, setConfirming] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const result = await logService.getLogs({ page, limit: 50, file: file || undefined, level: level || undefined, search: query || undefined, startTime: start || undefined, endTime: end || undefined }); setLogs(result.logs); setTotal(result.total); setPages(result.totalPages); } catch (reason) { if (String(reason).includes('401')) onSessionExpired(); else setError(reason instanceof Error ? reason.message : '日志加载失败'); } finally { setLoading(false); } };
  useEffect(() => { logService.getLogFiles().then(next => { setFiles(next); if (next[0]) setFile(current => current || next[0].name); }).catch(() => undefined); }, []);
  useEffect(() => { load(); }, [page, file, level, query, start, end]);
  useEffect(() => { if (!autoRefresh) return; const timer = window.setInterval(load, 5000); return () => window.clearInterval(timer); }, [autoRefresh, page, file, level, query, start, end]);
  const clear = async () => { try { await logService.clearLogs(file || undefined); setConfirming(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : '清空失败'); } };
  const exportLogs = async () => { try { const blob = await logService.exportLogs({ file: file || undefined, level: level || undefined, search: query || undefined, startTime: start || undefined, endTime: end || undefined }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `logs-${Date.now()}.txt`; anchor.click(); URL.revokeObjectURL(url); } catch (reason) { setError(reason instanceof Error ? reason.message : '导出失败'); } };
  const reset = () => { setLevel(''); setQuery(''); setStart(''); setEnd(''); setPage(1); };
  const badge = (value: string) => value.includes('ERROR') || value.includes('❌') ? 'bg-red-50 text-red-700' : value.includes('WARN') || value.includes('⚠️') ? 'bg-amber-50 text-amber-700' : 'bg-blue-50 text-blue-700';
  return <section className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="text-xs font-medium text-slate-600">日志文件<SelectMenu value={file} onChange={value => { setFile(value); setPage(1); }} ariaLabel="日志文件" className="mt-1.5 w-full" options={[{ value: '', label: '最新文件' }, ...files.map(item => ({ value: item.name, label: item.name }))]} /></label><label className="text-xs font-medium text-slate-600">级别<SelectMenu value={level} onChange={value => { setLevel(value); setPage(1); }} ariaLabel="日志级别" className="mt-1.5 w-full" options={[{ value: '', label: '全部级别' }, { value: 'ERROR', label: '错误' }, { value: 'WARN', label: '警告' }, { value: 'INFO', label: '信息' }, { value: 'DEBUG', label: '调试' }]} /></label><label className="text-xs font-medium text-slate-600">开始时间<input type="datetime-local" value={start} onChange={event => { setStart(event.target.value); setPage(1); }} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm" /></label><label className="text-xs font-medium text-slate-600">结束时间<input type="datetime-local" value={end} onChange={event => { setEnd(event.target.value); setPage(1); }} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm" /></label><div className="flex items-end gap-2"><button onClick={reset} className="rounded-xl border border-slate-300 px-3 py-2 text-sm text-slate-600">重置</button><button aria-label="刷新日志" onClick={load} className="rounded-xl bg-slate-900 px-3 py-2 text-sm text-white"><RefreshCw size={16} /></button></div></div><div className="mt-3 flex flex-wrap items-center gap-2"><div className="relative min-w-0 basis-full sm:basis-0 flex-1"><Search size={17} className="absolute left-3 top-2.5 text-slate-400" /><input aria-label="搜索日志内容" value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} placeholder="搜索日志内容…" className="w-full rounded-xl border border-slate-300 py-2 pl-9 pr-3 text-sm" /></div><label className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-3 py-2 text-sm text-slate-600"><input type="checkbox" checked={autoRefresh} onChange={event => setAutoRefresh(event.target.checked)} />自动刷新</label><button onClick={exportLogs} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-3 py-2 text-sm text-slate-700"><Download size={16} />导出</button><button onClick={() => setConfirming(true)} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-3 py-2 text-sm text-red-700 hover:bg-red-50"><Trash2 size={16} />清空</button></div></div>
    {error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 bg-slate-50 px-5 py-3"><div><p className="font-medium text-slate-800">日志记录</p><p className="mt-0.5 text-xs text-slate-500">共 {total} 条 {autoRefresh && '· 正在每 5 秒刷新'}</p></div></div>{loading ? <div className="p-12 text-center text-sm text-slate-500">正在加载日志…</div> : logs.length === 0 ? <div className="p-12 text-center"><FileText className="mx-auto text-slate-300" size={34} /><p className="mt-3 text-sm text-slate-500">暂无匹配的日志</p></div> : <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b border-slate-200 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">时间</th><th className="px-5 py-3">级别</th><th className="px-5 py-3">消息</th><th className="px-5 py-3" /></tr></thead><tbody>{logs.map((entry, index) => <tr key={`${entry.timestamp}-${index}`} className="border-b border-slate-100 last:border-0 hover:bg-slate-50"><td className="whitespace-nowrap px-5 py-3 text-xs text-slate-500">{new Date(entry.timestamp).toLocaleString('zh-CN')}</td><td className="px-5 py-3"><span className={`rounded-md px-2 py-1 text-xs font-medium ${badge(entry.level)}`}>{entry.level}</span></td><td className="max-w-xl truncate px-5 py-3 font-mono text-xs text-slate-700">{entry.message}</td><td className="px-5 py-3"><button aria-label="查看日志详情" onClick={() => setSelected(entry)} className="rounded-lg p-2 text-slate-500 hover:bg-blue-50 hover:text-blue-600"><Eye size={16} /></button></td></tr>)}</tbody></table></div>}{pages > 1 && <div className="flex items-center justify-between border-t border-slate-200 bg-slate-50 px-5 py-3 text-sm text-slate-600"><span>第 {page} / {pages} 页</span><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage(current => current - 1)} className="rounded-lg border border-slate-300 px-3 py-1.5 disabled:opacity-40">上一页</button><button disabled={page === pages} onClick={() => setPage(current => current + 1)} className="rounded-lg border border-slate-300 px-3 py-1.5 disabled:opacity-40">下一页</button></div></div>}</div>
    {confirming && <ConfirmClear file={file} onCancel={() => setConfirming(false)} onConfirm={clear} />}{selected && <div role="dialog" aria-modal="true" className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4"><div className="max-h-[80vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-semibold text-slate-950">日志详情</h2><button aria-label="关闭详情" onClick={() => setSelected(null)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={18} /></button></div><pre className="mt-5 whitespace-pre-wrap break-words rounded-xl bg-slate-950 p-4 text-xs leading-6 text-slate-100">{selected.raw}</pre></div></div>}</section>;
}
